/**
 * One-off generator: outputs Postman Collection v2.1 JSON for this repo.
 * Run: node scripts/gen_postman_collection.js
 */
const fs = require('fs');
const path = require('path');

const R = (name, method, p, desc = '') => ({
  name: desc || `${method} ${p}`,
  request: {
    method,
    header: [
      { key: 'Content-Type', value: 'application/json' },
      { key: 'Authorization', value: 'Bearer {{token}}', disabled: true, description: 'Enable for protected routes' },
    ],
    url: '{{baseUrl}}' + p,
  },
});

const folders = [
  [
    '00 — Health',
    [R('Health', 'GET', '/health')],
  ],
  [
    '01 — Admin & Auth',
    [
      R('Admin login', 'POST', '/api/admin/login', 'Body: email, password — set token from response'),
      R('Admin register', 'POST', '/api/admin/register'),
      R('Admin getAll', 'GET', '/api/admin/getAll'),
      R('Admin getAll by category', 'GET', '/api/admin/getAll/farmer'),
      R('Admin update', 'PUT', '/api/admin/update/1'),
      R('Admin delete', 'DELETE', '/api/admin/delete/1'),
      R('Admin screens', 'GET', '/api/admin/screens'),
      R('Auth me', 'GET', '/api/auth/me'),
      R('Auth notifications', 'GET', '/api/auth/notifications'),
      R('Auth change-password', 'POST', '/api/auth/change-password'),
    ],
  ],
  [
    '02 — SAP (legacy dashboard / sync)',
    [
      R('SAP dashboard', 'GET', '/api/sap/dashboard'),
      R('Sync bird-receipt', 'GET', '/api/sap/sync/bird-receipt'),
      R('Sync feed-medicine', 'GET', '/api/sap/sync/feed-medicine'),
      R('Sync laying', 'GET', '/api/sap/sync/laying'),
      R('Sync mortality', 'GET', '/api/sap/sync/mortality'),
      R('Sync culls-kill', 'GET', '/api/sap/sync/culls-kill'),
      R('Sync culls-sale', 'GET', '/api/sap/sync/culls-sale'),
      R('Sync estimated-cost', 'GET', '/api/sap/sync/estimated-cost'),
      R('Get bird-receipt', 'GET', '/api/sap/bird-receipt'),
      R('Get feed-medicine', 'GET', '/api/sap/feed-medicine'),
      R('Get laying', 'GET', '/api/sap/laying'),
      R('Get mortality', 'GET', '/api/sap/mortality'),
      R('Get culls-kill', 'GET', '/api/sap/culls-kill'),
      R('Get culls-sale', 'GET', '/api/sap/culls-sale'),
      R('Get estimated-cost', 'GET', '/api/sap/estimated-cost'),
    ],
  ],
  [
    '03 — SAP Live (dropdowns)',
    [
      R('Plants', 'GET', '/api/sap-live/plants'),
      R('Orders', 'GET', '/api/sap-live/orders?module=feed_med&werks=1901'),
      R('Flocks', 'GET', '/api/sap-live/flocks?module=feed_med&werks=1901&aufnr=190125000082'),
      R('Chain', 'GET', '/api/sap-live/chain?module=feed_med&werks=1901'),
    ],
  ],
  [
    '04 — SAP Sync (local ↔ SAP)',
    [
      R('Mark synced', 'POST', '/api/sap-sync'),
      R('Sync status', 'GET', '/api/sap-sync/status?module=feeding&record_id=1'),
      R('List unsynced (admin)', 'GET', '/api/sap-sync/unsynced?plant_code=1901&limit=30'),
      R('Push unsynced bulk (admin)', 'POST', '/api/sap-sync/push-unsynced'),
      R('Pull from SAP', 'POST', '/api/sap-sync/pull'),
      R('Push to SAP', 'POST', '/api/sap-sync/push'),
      R('Push raw', 'POST', '/api/sap-sync/push-raw'),
    ],
  ],
  [
    '05 — Daily activity & feeding',
    [
      R('SAP materials', 'GET', '/api/daily-activity/sap/materials?plant_code=1901'),
      R('SAP sync-to-master', 'POST', '/api/daily-activity/sap/sync-to-master'),
      R('Plants', 'GET', '/api/daily-activity/plants'),
      R('Flock grid', 'GET', '/api/daily-activity/flocks'),
      R('Activity menu', 'GET', '/api/daily-activity/flock-detail/LY000001'),
      R('Feeding items', 'GET', '/api/daily-activity/feeding/items?plant_code=1901&type=feed'),
      R('Stock', 'GET', '/api/daily-activity/feeding/stock?plant_code=1901&type=medicine'),
      R('Feeding data', 'GET', '/api/daily-activity/feeding/LY000001?date=2026-05-05'),
      R('Feeding save', 'POST', '/api/daily-activity/feeding/save'),
      R('Master feed list', 'GET', '/api/daily-activity/master/feed'),
      R('Master feed add', 'POST', '/api/daily-activity/master/feed'),
      R('Master feed update', 'PUT', '/api/daily-activity/master/feed/1'),
      R('Master feed delete', 'DELETE', '/api/daily-activity/master/feed/1'),
      R('Master water list', 'GET', '/api/daily-activity/master/water'),
      R('Master water add', 'POST', '/api/daily-activity/master/water'),
      R('Master water update', 'PUT', '/api/daily-activity/master/water/1'),
      R('Master water delete', 'DELETE', '/api/daily-activity/master/water/1'),
      R('Master medicine list', 'GET', '/api/daily-activity/master/medicine'),
      R('Master medicine add', 'POST', '/api/daily-activity/master/medicine'),
      R('Master medicine update', 'PUT', '/api/daily-activity/master/medicine/1'),
      R('Master medicine delete', 'DELETE', '/api/daily-activity/master/medicine/1'),
      R('Master others list', 'GET', '/api/daily-activity/master/others'),
      R('Master others add', 'POST', '/api/daily-activity/master/others'),
      R('Master others update', 'PUT', '/api/daily-activity/master/others/1'),
      R('Master others delete', 'DELETE', '/api/daily-activity/master/others/1'),
      R('Master stock list', 'GET', '/api/daily-activity/master/stock'),
      R('Master stock add', 'POST', '/api/daily-activity/master/stock'),
      R('Master stock update', 'PUT', '/api/daily-activity/master/stock/1'),
    ],
  ],
  [
    '06 — Egg collection v2',
    [
      R('Dropdowns', 'GET', '/api/egg-collection/v2/dropdowns?plant_code=1901&flock_no=LY000001'),
      R('Sheds', 'GET', '/api/egg-collection/v2/sheds?plant_code=1901'),
      R('Parts', 'GET', '/api/egg-collection/v2/parts?shed_id=1'),
      R('Lines', 'GET', '/api/egg-collection/v2/lines?part_id=1'),
      R('Egg types', 'GET', '/api/egg-collection/v2/egg-types'),
      R('Save collection', 'POST', '/api/egg-collection/v2/save'),
      R('Get entry', 'GET', '/api/egg-collection/v2/entry?flock_no=LY000001&date=2026-05-05'),
      R('List collections', 'GET', '/api/egg-collection/v2/list'),
      R('Delete collection', 'DELETE', '/api/egg-collection/v2/1'),
    ],
  ],
  [
    '07 — Egg collection (legacy)',
    [
      R('Sheds', 'GET', '/api/egg-collection/sheds?plant_code=1901'),
      R('Shed lines', 'GET', '/api/egg-collection/sheds/1/lines'),
      R('Egg types', 'GET', '/api/egg-collection/egg-types'),
      R('Summary', 'GET', '/api/egg-collection/summary'),
      R('Save', 'POST', '/api/egg-collection/save'),
      R('List', 'GET', '/api/egg-collection/list'),
      R('Get by date/id', 'GET', '/api/egg-collection/2026-05-05/1'),
    ],
  ],
  [
    '08 — Feeding (legacy stock)',
    [
      R('Push stock SAP', 'POST', '/api/feeding/sap/push-stock'),
      R('Consume', 'POST', '/api/feeding/consume'),
      R('Add other item', 'POST', '/api/feeding/other/item'),
      R('Remove other item', 'DELETE', '/api/feeding/other/item/1'),
      R('Consumption history', 'GET', '/api/feeding/consumption/history'),
      R('Items by category', 'GET', '/api/feeding/feed'),
    ],
  ],
  [
    '09 — Bird weighing',
    [
      R('Save', 'POST', '/api/bird-weighing/save'),
      R('Entry by date', 'GET', '/api/bird-weighing/entry/2026-05-05'),
      R('List', 'GET', '/api/bird-weighing/list'),
    ],
  ],
  [
    '10 — Vaccination',
    [
      R('Schedule list', 'GET', '/api/vaccination/schedule'),
      R('Schedule add', 'POST', '/api/vaccination/schedule'),
      R('Schedule update', 'PUT', '/api/vaccination/schedule/1'),
      R('Schedule delete', 'DELETE', '/api/vaccination/schedule/1'),
    ],
  ],
  [
    '11 — Vaccination schedule (mobile)',
    [
      R('Notifications', 'GET', '/api/vaccination-schedule/notifications'),
      R('Record vaccination', 'POST', '/api/vaccination-schedule/record'),
      R('Today', 'GET', '/api/vaccination-schedule/today'),
      R('Flock schedule', 'GET', '/api/vaccination-schedule/flock/LY000001'),
      R('Generate', 'POST', '/api/vaccination-schedule/generate'),
      R('Generate all', 'POST', '/api/vaccination-schedule/generate-all'),
    ],
  ],
  [
    '12 — Vaccination master',
    [
      R('Programs', 'GET', '/api/vaccination-master/programs'),
      R('Program by id', 'GET', '/api/vaccination-master/programs/1'),
      R('Create program', 'POST', '/api/vaccination-master/programs'),
      R('Update program', 'PUT', '/api/vaccination-master/programs/1'),
      R('Delete program', 'DELETE', '/api/vaccination-master/programs/1'),
      R('Program details', 'GET', '/api/vaccination-master/programs/1/details'),
      R('Add detail', 'POST', '/api/vaccination-master/programs/1/details'),
      R('Add details bulk', 'POST', '/api/vaccination-master/programs/1/details/bulk'),
      R('Update detail', 'PUT', '/api/vaccination-master/details/1'),
      R('Delete detail', 'DELETE', '/api/vaccination-master/details/1'),
      R('Upload excel', 'POST', '/api/vaccination-master/programs/1/upload-excel'),
      R('Download template', 'GET', '/api/vaccination-master/template'),
    ],
  ],
  [
    '13 — Vaccination admin',
    [
      R('Programs', 'GET', '/api/vaccination-admin/programs'),
      R('Current program', 'GET', '/api/vaccination-admin/programs/current'),
      R('Program details', 'GET', '/api/vaccination-admin/programs/1/details'),
      R('Add detail line', 'POST', '/api/vaccination-admin/programs/1/details'),
      R('Upload new version', 'POST', '/api/vaccination-admin/programs/upload-new-version'),
      R('Template', 'GET', '/api/vaccination-admin/template'),
      R('Flock dropdown', 'GET', '/api/vaccination-admin/flock-dropdown'),
      R('Flock grid', 'GET', '/api/vaccination-admin/flock-grid/LY000001'),
      R('Record missed', 'POST', '/api/vaccination-admin/record-missed'),
      R('Record missed bulk', 'POST', '/api/vaccination-admin/record-missed/bulk'),
    ],
  ],
  [
    '14 — Notifications',
    [
      R('List', 'GET', '/api/notifications'),
      R('Mark all read', 'PUT', '/api/notifications/mark-all-read'),
      R('Trigger check', 'POST', '/api/notifications/trigger-check'),
      R('Farm config', 'GET', '/api/notifications/farm-config'),
      R('Flock start date', 'PUT', '/api/notifications/flock-start-date'),
      R('Mark read', 'PUT', '/api/notifications/1/read'),
    ],
  ],
  [
    '15 — Biosecurity notifications',
    [
      R('Pending', 'GET', '/api/biosec-notifications'),
      R('Entry screen', 'GET', '/api/biosec-notifications/entry-screen'),
    ],
  ],
  [
    '16 — Farms',
    [
      R('List farms', 'GET', '/api/farms'),
      R('Create farm', 'POST', '/api/farms'),
      R('Farm flocks', 'GET', '/api/farms/1/flocks'),
      R('Add flock to farm', 'POST', '/api/farms/1/flocks'),
    ],
  ],
  [
    '17 — Flock & farmer master',
    [
      R('Flock dropdown', 'GET', '/api/flock-master/dropdown'),
      R('Flock by no', 'GET', '/api/flock-master/LY000001'),
      R('Flock master list', 'GET', '/api/flock-master'),
      R('Farmer dropdown', 'GET', '/api/farmer-master/dropdown'),
      R('Farmer lines', 'GET', '/api/farmer-master/lines'),
      R('Farmer by number', 'GET', '/api/farmer-master/F001'),
      R('Farmer master list', 'GET', '/api/farmer-master'),
    ],
  ],
  [
    '18 — Breeder entries',
    [
      R('Flocks', 'GET', '/api/breeder/flocks'),
      R('Opening stock', 'GET', '/api/breeder/flock/1/opening-stock'),
      R('Save entry', 'POST', '/api/breeder/entry'),
      R('Get entry', 'GET', '/api/breeder/entry/1/2026-05-05'),
      R('Entries', 'GET', '/api/breeder/entries/1'),
    ],
  ],
  [
    '19 — Mortality / Cull (mortality-cull)',
    [
      R('Flocks', 'GET', '/api/mortality-cull/flocks?plant_code=1901'),
      R('Sheds', 'GET', '/api/mortality-cull/sheds?plant_code=1901'),
      R('Parts', 'GET', '/api/mortality-cull/parts?shed_id=1'),
      R('Lines', 'GET', '/api/mortality-cull/lines?part_id=1'),
      R('Mortality save', 'POST', '/api/mortality-cull/mortality/save'),
      R('Mortality get', 'GET', '/api/mortality-cull/mortality/LY000001?date=2026-05-05'),
      R('Cull kill save', 'POST', '/api/mortality-cull/cull-kill/save'),
      R('Cull kill get', 'GET', '/api/mortality-cull/cull-kill/LY000001?date=2026-05-05'),
      R('Master mortality reasons', 'GET', '/api/mortality-cull/master/mortality-reasons'),
      R('Master cull-kill reasons', 'GET', '/api/mortality-cull/master/cull-kill-reasons'),
      R('Master mortality photo types', 'GET', '/api/mortality-cull/master/mortality-photo-types'),
      R('Master cull-kill photo types', 'GET', '/api/mortality-cull/master/cull-kill-photo-types'),
      R('Master mortality reasons POST', 'POST', '/api/mortality-cull/master/mortality-reasons'),
      R('Master mortality reasons PUT', 'PUT', '/api/mortality-cull/master/mortality-reasons/1'),
      R('Master mortality reasons DELETE', 'DELETE', '/api/mortality-cull/master/mortality-reasons/1'),
      R('Master cull reasons POST', 'POST', '/api/mortality-cull/master/cull-kill-reasons'),
      R('Master cull reasons PUT', 'PUT', '/api/mortality-cull/master/cull-kill-reasons/1'),
      R('Master cull reasons DELETE', 'DELETE', '/api/mortality-cull/master/cull-kill-reasons/1'),
      R('Master mortality photo POST', 'POST', '/api/mortality-cull/master/mortality-photo-types'),
      R('Master mortality photo PUT', 'PUT', '/api/mortality-cull/master/mortality-photo-types/1'),
      R('Master cull photo POST', 'POST', '/api/mortality-cull/master/cull-kill-photo-types'),
      R('Master cull photo PUT', 'PUT', '/api/mortality-cull/master/cull-kill-photo-types/1'),
    ],
  ],
  [
    '20 — Farm module (mortalityCullKill)',
    [
      R('Sheds', 'GET', '/api/farm/sheds'),
      R('Parts', 'GET', '/api/farm/parts'),
      R('Lines', 'GET', '/api/farm/lines'),
      R('Line info', 'GET', '/api/farm/line-info'),
      R('Mortality reasons', 'GET', '/api/farm/mortality/reasons'),
      R('Mortality photo types', 'GET', '/api/farm/mortality/photo-types'),
      R('Mortality save', 'POST', '/api/farm/mortality/save'),
      R('Mortality get', 'GET', '/api/farm/mortality/LY000001?date=2026-05-05'),
      R('Cull-kill reasons', 'GET', '/api/farm/cull-kill/reasons'),
      R('Cull-kill photo types', 'GET', '/api/farm/cull-kill/photo-types'),
      R('Cull-kill save', 'POST', '/api/farm/cull-kill/save'),
      R('Cull-kill get', 'GET', '/api/farm/cull-kill/LY000001?date=2026-05-05'),
      R('Admin sheds list', 'GET', '/api/farm/admin/sheds'),
      R('Admin parts list', 'GET', '/api/farm/admin/parts?shed_id=1'),
      R('Admin lines list', 'GET', '/api/farm/admin/lines?part_id=1'),
      R('Admin mortality reasons CRUD', 'GET', '/api/farm/admin/mortality-reasons'),
      R('Admin cull reasons CRUD', 'GET', '/api/farm/admin/cull-reasons'),
      R('Admin mortality photo types CRUD', 'GET', '/api/farm/admin/mortality-photo-types'),
      R('Admin cull photo types CRUD', 'GET', '/api/farm/admin/cull-photo-types'),
      R('Admin sheds POST', 'POST', '/api/farm/admin/sheds'),
      R('Admin sheds PUT', 'PUT', '/api/farm/admin/sheds/1'),
      R('Admin sheds DELETE', 'DELETE', '/api/farm/admin/sheds/1'),
      R('Admin parts POST', 'POST', '/api/farm/admin/parts'),
      R('Admin parts PUT', 'PUT', '/api/farm/admin/parts/1'),
      R('Admin parts DELETE', 'DELETE', '/api/farm/admin/parts/1'),
      R('Admin lines POST', 'POST', '/api/farm/admin/lines'),
      R('Admin lines PUT', 'PUT', '/api/farm/admin/lines/1'),
      R('Admin lines DELETE', 'DELETE', '/api/farm/admin/lines/1'),
      R('Admin mortality reasons POST', 'POST', '/api/farm/admin/mortality-reasons'),
      R('Admin cull reasons POST', 'POST', '/api/farm/admin/cull-reasons'),
      R('Admin mortality photo POST', 'POST', '/api/farm/admin/mortality-photo-types'),
      R('Admin cull photo POST', 'POST', '/api/farm/admin/cull-photo-types'),
    ],
  ],
  [
    '21 — Cull sales',
    [
      R('Flocks', 'GET', '/api/cull-sales/flocks?plant_code=1901'),
      R('Sheds', 'GET', '/api/cull-sales/sheds?plant_code=1901'),
      R('Parts', 'GET', '/api/cull-sales/parts?shed_id=1'),
      R('Lines', 'GET', '/api/cull-sales/lines?part_id=1'),
      R('Dropdowns', 'GET', '/api/cull-sales/dropdowns?plant_code=1901'),
      R('Customer types', 'GET', '/api/cull-sales/customer-types'),
      R('Customers', 'GET', '/api/cull-sales/customers?plant_code=1901'),
      R('Sales types', 'GET', '/api/cull-sales/sales-types'),
      R('Transport types', 'GET', '/api/cull-sales/transport-types'),
      R('Order by', 'GET', '/api/cull-sales/order-by?plant_code=1901'),
      R('Dispatched by', 'GET', '/api/cull-sales/dispatched-by?plant_code=1901'),
      R('Master sync POST', 'POST', '/api/cull-sales/masters/sync/customer_types'),
      R('Master sync GET', 'GET', '/api/cull-sales/masters/sync/customer_types'),
      R('Master getAll', 'GET', '/api/cull-sales/masters/getAll/customer_types'),
      R('Calculate load', 'GET', '/api/cull-sales/calculate-load'),
      R('Save', 'POST', '/api/cull-sales/save'),
      R('Get all', 'GET', '/api/cull-sales/getAll'),
      R('Get one', 'GET', '/api/cull-sales/getOne/1'),
      R('By flock', 'GET', '/api/cull-sales/flock/LY000001'),
      R('DC PDF', 'GET', '/api/cull-sales/dc/1'),
      R('Delete', 'DELETE', '/api/cull-sales/1'),
    ],
  ],
  [
    '22 — Masters (/api/masters — newMasters + masters)',
    [
      R('Shed list', 'GET', '/api/masters/shed?plant_code=1901'),
      R('Shed add', 'POST', '/api/masters/shed'),
      R('Shed part add', 'POST', '/api/masters/shed/1/part'),
      R('Shed part update', 'PUT', '/api/masters/shed/part/1'),
      R('Shed part delete', 'DELETE', '/api/masters/shed/part/1'),
      R('Shed line add', 'POST', '/api/masters/shed/part/1/line'),
      R('Shed line update', 'PUT', '/api/masters/shed/line/1'),
      R('Shed line delete', 'DELETE', '/api/masters/shed/line/1'),
      R('Shed update', 'PUT', '/api/masters/shed/1'),
      R('Shed delete', 'DELETE', '/api/masters/shed/1'),
      R('Standard weight list', 'GET', '/api/masters/standard-weight'),
      R('Standard weight by id', 'GET', '/api/masters/standard-weight/1'),
      R('Standard weight add', 'POST', '/api/masters/standard-weight'),
      R('Standard weight update week row', 'PUT', '/api/masters/standard-weight/week/1'),
      R('Standard weight delete week row', 'DELETE', '/api/masters/standard-weight/week/1'),
      R('Standard weight update', 'PUT', '/api/masters/standard-weight/1'),
      R('Standard weight delete', 'DELETE', '/api/masters/standard-weight/1'),
      R('Standard weight add week row', 'POST', '/api/masters/standard-weight/1/weeks'),
      R('Standard weight (masters.js) add week', 'POST', '/api/masters/standard-weight/1/week'),
      R('Mortality-cull reasons', 'GET', '/api/masters/mortality-cull-reasons?module=Mortality'),
      R('Mortality-cull reasons add', 'POST', '/api/masters/mortality-cull-reasons'),
      R('Mortality-cull reasons update', 'PUT', '/api/masters/mortality-cull-reasons/1'),
      R('Mortality-cull reasons delete', 'DELETE', '/api/masters/mortality-cull-reasons/1'),
      R('Bird grading list', 'GET', '/api/masters/bird-grading'),
      R('Bird grading add', 'POST', '/api/masters/bird-grading'),
      R('Bird grading update', 'PUT', '/api/masters/bird-grading/1'),
      R('Bird grading delete', 'DELETE', '/api/masters/bird-grading/1'),
      R('Egg grading list', 'GET', '/api/masters/egg-grading'),
      R('Egg grading add', 'POST', '/api/masters/egg-grading'),
      R('Egg grading update', 'PUT', '/api/masters/egg-grading/1'),
      R('Egg grading delete', 'DELETE', '/api/masters/egg-grading/1'),
      R('Egg types list', 'GET', '/api/masters/egg-types'),
      R('Egg types add', 'POST', '/api/masters/egg-types'),
      R('Egg types update', 'PUT', '/api/masters/egg-types/1'),
      R('Egg types delete', 'DELETE', '/api/masters/egg-types/1'),
    ],
  ],
  [
    '24 — Breeder supply',
    [
      R('Get all', 'GET', '/api/breeder-supply/getAll'),
      R('Get one', 'GET', '/api/breeder-supply/getOne/1'),
      R('Create', 'POST', '/api/breeder-supply/create'),
      R('Update', 'PUT', '/api/breeder-supply/update/1'),
      R('Remove', 'DELETE', '/api/breeder-supply/remove/1'),
    ],
  ],
  [
    '25 — Supervisor',
    [
      R('List', 'GET', '/api/supervisor'),
      R('Create', 'POST', '/api/supervisor'),
      R('Update', 'PUT', '/api/supervisor/1'),
      R('Assign shift', 'POST', '/api/supervisor/shift'),
      R('Shifts', 'GET', '/api/supervisor/shifts'),
      R('My plant', 'GET', '/api/supervisor/my-plant'),
    ],
  ],
  [
    '26 — Schedule',
    [
      R('Generate', 'POST', '/api/schedule/generate'),
      R('Today', 'GET', '/api/schedule/today'),
      R('Overdue', 'GET', '/api/schedule/overdue'),
      R('Completion report', 'GET', '/api/schedule/completion'),
      R('Late reasons', 'GET', '/api/schedule/late-reasons'),
      R('Complete', 'POST', '/api/schedule/complete'),
      R('Trigger check', 'POST', '/api/schedule/trigger-check'),
    ],
  ],
  [
    '27 — Calendar',
    [
      R('Today due', 'GET', '/api/calendar/today'),
      R('Flock calendar', 'GET', '/api/calendar/flock/LY000001'),
      R('Special days', 'GET', '/api/calendar/flock/LY000001/special'),
    ],
  ],
  [
    '28 — Mobile activities',
    [
      R('Activities root', 'GET', '/api/mobile/activities'),
      R('Frequencies', 'GET', '/api/mobile/activities/frequencies'),
      R('Water quality dropdowns', 'GET', '/api/mobile/activities/dropdowns/water-quality'),
      R('Dropdowns', 'GET', '/api/mobile/activities/dropdowns'),
    ],
  ],
  [
    '29 — Mobile tasks (biosecurity)',
    [
      R('POST frequency', 'POST', '/api/mobile/tasks/daily'),
      R('POST with images', 'POST', '/api/mobile/tasks/daily/with-images'),
      R('GET frequency', 'GET', '/api/mobile/tasks/daily'),
      R('History', 'GET', '/api/mobile/tasks/daily/history'),
      R('Date info', 'GET', '/api/mobile/tasks/daily/date-info'),
    ],
  ],
  [
    '30 — Admin categories & activities',
    [
      R('Categories list', 'GET', '/api/admin/categories'),
      R('Categories create', 'POST', '/api/admin/categories'),
      R('Categories update', 'PUT', '/api/admin/categories/1'),
      R('Categories delete', 'DELETE', '/api/admin/categories/1'),
      R('Activities list', 'GET', '/api/admin/activities'),
      R('Activities create', 'POST', '/api/admin/activities'),
      R('Activities update', 'PUT', '/api/admin/activities/1'),
      R('Activities toggle', 'PATCH', '/api/admin/activities/1/toggle'),
      R('Activities delete', 'DELETE', '/api/admin/activities/1'),
    ],
  ],
  [
    '31 — Admin grid & edit',
    [
      R('Dropdowns', 'GET', '/api/admin/grid/dropdowns'),
      R('Shed parts', 'GET', '/api/admin/grid/sheds/1/parts'),
      R('Part lines', 'GET', '/api/admin/grid/parts/1/lines'),
      R('Daily feed grid', 'GET', '/api/admin/grid/daily-feed'),
      R('Daily feed detail', 'GET', '/api/admin/grid/daily-feed/detail'),
      R('Delete feed by date', 'DELETE', '/api/admin/grid/daily-feed/date'),
      R('Delete feed entry', 'DELETE', '/api/admin/grid/daily-feed/1'),
      R('Edit feeding', 'GET', '/api/admin/grid/edit/feeding/LY000001'),
      R('Update feeding', 'PUT', '/api/admin/grid/edit/feeding/LY000001'),
      R('Mortality grid', 'GET', '/api/admin/grid/mortality'),
      R('Mortality detail', 'GET', '/api/admin/grid/mortality/1'),
      R('Delete mortality', 'DELETE', '/api/admin/grid/mortality/1'),
      R('Edit mortality', 'GET', '/api/admin/grid/edit/mortality/1'),
      R('Update mortality', 'PUT', '/api/admin/grid/edit/mortality/1'),
      R('Cull-kill grid', 'GET', '/api/admin/grid/cull-kill'),
      R('Cull-kill detail', 'GET', '/api/admin/grid/cull-kill/1'),
      R('Delete cull-kill', 'DELETE', '/api/admin/grid/cull-kill/1'),
      R('Edit cull-kill', 'GET', '/api/admin/grid/edit/cull-kill/1'),
      R('Update cull-kill', 'PUT', '/api/admin/grid/edit/cull-kill/1'),
      R('Egg grid', 'GET', '/api/admin/grid/egg-collection'),
      R('Egg detail', 'GET', '/api/admin/grid/egg-collection/1'),
      R('Delete egg', 'DELETE', '/api/admin/grid/egg-collection/1'),
      R('Edit egg', 'GET', '/api/admin/grid/edit/egg-collection/1'),
      R('Update egg', 'PUT', '/api/admin/grid/edit/egg-collection/1'),
    ],
  ],
  [
    '32 — Roles',
    [
      R('Roles by category', 'GET', '/api/roles/getAll/farmer'),
      R('Roles all', 'GET', '/api/roles/getAll'),
      R('Add role', 'POST', '/api/roles/add'),
      R('Update role', 'PUT', '/api/roles/update/1'),
      R('Delete role', 'DELETE', '/api/roles/delete/1'),
    ],
  ],
];

const collection = {
  info: {
    name: 'KRISHI Breeder API — Complete',
    description:
      'Generated list of routes in this codebase. Set {{baseUrl}} (e.g. http://localhost:3000). For protected routes, login via POST /api/admin/login and paste JWT into collection variable `token`, then enable the Authorization header on requests (or use Postman Authorization tab).\n\nSome folders duplicate mount paths (/api/masters is registered twice — newMasters + masters).\n\nPhoto uploads (mortality save) need multipart/form-data — adjust in Postman.',
    schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
  },
  variable: [
    { key: 'baseUrl', value: 'http://localhost:3000' },
    { key: 'token', value: '' },
  ],
  item: folders.map(([name, items]) => ({
    name,
    item: items,
  })),
};

const out = path.join(__dirname, '..', 'KRISHI-Breeder-API-Complete.postman_collection.json');
fs.writeFileSync(out, JSON.stringify(collection, null, 2), 'utf8');
console.log('Wrote', out);
